name: "Hello wrold workflow"

on:
    push:
        branches:
            - main
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"
            - name: "print current date"
              run: date            

   

