name: "multi event pipeline"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    on-push: #job1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name : "run on mutli event"
              run: echo "multi event push"    
    on-pull_request: #job2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "pull request"
              run: echo "pull requested"     
    on-workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "workflow dispatch"
              run: echo "on work flow retrigger"  

